spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: customer
      host: localhost
      port: 27017
      authentication-database: admin
  kafka:
    consumer:
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.oubrik.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.oubrik.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040